// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "marketdata.proto" (package "tinkoff.public.invest.api.contract.v1", syntax proto3)
// tslint:disable
import { MarketDataStreamService } from "./marketdata.js";
import type { MarketDataServerSideStreamRequest } from "./marketdata.js";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { MarketDataResponse } from "./marketdata.js";
import type { MarketDataRequest } from "./marketdata.js";
import type { DuplexStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MarketDataService } from "./marketdata.js";
import type { GetClosePricesResponse } from "./marketdata.js";
import type { GetClosePricesRequest } from "./marketdata.js";
import type { GetLastTradesResponse } from "./marketdata.js";
import type { GetLastTradesRequest } from "./marketdata.js";
import type { GetTradingStatusResponse } from "./marketdata.js";
import type { GetTradingStatusRequest } from "./marketdata.js";
import type { GetOrderBookResponse } from "./marketdata.js";
import type { GetOrderBookRequest } from "./marketdata.js";
import type { GetLastPricesResponse } from "./marketdata.js";
import type { GetLastPricesRequest } from "./marketdata.js";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetCandlesResponse } from "./marketdata.js";
import type { GetCandlesRequest } from "./marketdata.js";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Сервис получения биржевой информации:</br> **1**. свечи;</br> **2**. стаканы;</br> **3**. торговые статусы;</br> **4**. лента сделок.
 *
 * @generated from protobuf service tinkoff.public.invest.api.contract.v1.MarketDataService
 */
export interface IMarketDataServiceClient {
    /**
     * Метод запроса исторических свечей по инструменту.
     *
     * @generated from protobuf rpc: GetCandles(tinkoff.public.invest.api.contract.v1.GetCandlesRequest) returns (tinkoff.public.invest.api.contract.v1.GetCandlesResponse);
     */
    getCandles(input: GetCandlesRequest, options?: RpcOptions): UnaryCall<GetCandlesRequest, GetCandlesResponse>;
    /**
     * Метод запроса цен последних сделок по инструментам.
     *
     * @generated from protobuf rpc: GetLastPrices(tinkoff.public.invest.api.contract.v1.GetLastPricesRequest) returns (tinkoff.public.invest.api.contract.v1.GetLastPricesResponse);
     */
    getLastPrices(input: GetLastPricesRequest, options?: RpcOptions): UnaryCall<GetLastPricesRequest, GetLastPricesResponse>;
    /**
     * Метод получения стакана по инструменту.
     *
     * @generated from protobuf rpc: GetOrderBook(tinkoff.public.invest.api.contract.v1.GetOrderBookRequest) returns (tinkoff.public.invest.api.contract.v1.GetOrderBookResponse);
     */
    getOrderBook(input: GetOrderBookRequest, options?: RpcOptions): UnaryCall<GetOrderBookRequest, GetOrderBookResponse>;
    /**
     * Метод запроса статуса торгов по инструментам.
     *
     * @generated from protobuf rpc: GetTradingStatus(tinkoff.public.invest.api.contract.v1.GetTradingStatusRequest) returns (tinkoff.public.invest.api.contract.v1.GetTradingStatusResponse);
     */
    getTradingStatus(input: GetTradingStatusRequest, options?: RpcOptions): UnaryCall<GetTradingStatusRequest, GetTradingStatusResponse>;
    /**
     * Метод запроса обезличенных сделок за последний час.
     *
     * @generated from protobuf rpc: GetLastTrades(tinkoff.public.invest.api.contract.v1.GetLastTradesRequest) returns (tinkoff.public.invest.api.contract.v1.GetLastTradesResponse);
     */
    getLastTrades(input: GetLastTradesRequest, options?: RpcOptions): UnaryCall<GetLastTradesRequest, GetLastTradesResponse>;
    /**
     * Метод запроса цен закрытия торговой сессии по инструментам.
     *
     * @generated from protobuf rpc: GetClosePrices(tinkoff.public.invest.api.contract.v1.GetClosePricesRequest) returns (tinkoff.public.invest.api.contract.v1.GetClosePricesResponse);
     */
    getClosePrices(input: GetClosePricesRequest, options?: RpcOptions): UnaryCall<GetClosePricesRequest, GetClosePricesResponse>;
}
/**
 * Сервис получения биржевой информации:</br> **1**. свечи;</br> **2**. стаканы;</br> **3**. торговые статусы;</br> **4**. лента сделок.
 *
 * @generated from protobuf service tinkoff.public.invest.api.contract.v1.MarketDataService
 */
export class MarketDataServiceClient implements IMarketDataServiceClient, ServiceInfo {
    typeName = MarketDataService.typeName;
    methods = MarketDataService.methods;
    options = MarketDataService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Метод запроса исторических свечей по инструменту.
     *
     * @generated from protobuf rpc: GetCandles(tinkoff.public.invest.api.contract.v1.GetCandlesRequest) returns (tinkoff.public.invest.api.contract.v1.GetCandlesResponse);
     */
    getCandles(input: GetCandlesRequest, options?: RpcOptions): UnaryCall<GetCandlesRequest, GetCandlesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCandlesRequest, GetCandlesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод запроса цен последних сделок по инструментам.
     *
     * @generated from protobuf rpc: GetLastPrices(tinkoff.public.invest.api.contract.v1.GetLastPricesRequest) returns (tinkoff.public.invest.api.contract.v1.GetLastPricesResponse);
     */
    getLastPrices(input: GetLastPricesRequest, options?: RpcOptions): UnaryCall<GetLastPricesRequest, GetLastPricesResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetLastPricesRequest, GetLastPricesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод получения стакана по инструменту.
     *
     * @generated from protobuf rpc: GetOrderBook(tinkoff.public.invest.api.contract.v1.GetOrderBookRequest) returns (tinkoff.public.invest.api.contract.v1.GetOrderBookResponse);
     */
    getOrderBook(input: GetOrderBookRequest, options?: RpcOptions): UnaryCall<GetOrderBookRequest, GetOrderBookResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOrderBookRequest, GetOrderBookResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод запроса статуса торгов по инструментам.
     *
     * @generated from protobuf rpc: GetTradingStatus(tinkoff.public.invest.api.contract.v1.GetTradingStatusRequest) returns (tinkoff.public.invest.api.contract.v1.GetTradingStatusResponse);
     */
    getTradingStatus(input: GetTradingStatusRequest, options?: RpcOptions): UnaryCall<GetTradingStatusRequest, GetTradingStatusResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTradingStatusRequest, GetTradingStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод запроса обезличенных сделок за последний час.
     *
     * @generated from protobuf rpc: GetLastTrades(tinkoff.public.invest.api.contract.v1.GetLastTradesRequest) returns (tinkoff.public.invest.api.contract.v1.GetLastTradesResponse);
     */
    getLastTrades(input: GetLastTradesRequest, options?: RpcOptions): UnaryCall<GetLastTradesRequest, GetLastTradesResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetLastTradesRequest, GetLastTradesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод запроса цен закрытия торговой сессии по инструментам.
     *
     * @generated from protobuf rpc: GetClosePrices(tinkoff.public.invest.api.contract.v1.GetClosePricesRequest) returns (tinkoff.public.invest.api.contract.v1.GetClosePricesResponse);
     */
    getClosePrices(input: GetClosePricesRequest, options?: RpcOptions): UnaryCall<GetClosePricesRequest, GetClosePricesResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetClosePricesRequest, GetClosePricesResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service tinkoff.public.invest.api.contract.v1.MarketDataStreamService
 */
export interface IMarketDataStreamServiceClient {
    /**
     * Bi-directional стрим предоставления биржевой информации.
     *
     * @generated from protobuf rpc: MarketDataStream(stream tinkoff.public.invest.api.contract.v1.MarketDataRequest) returns (stream tinkoff.public.invest.api.contract.v1.MarketDataResponse);
     */
    marketDataStream(options?: RpcOptions): DuplexStreamingCall<MarketDataRequest, MarketDataResponse>;
    /**
     * Server-side стрим предоставления биржевой информации.
     *
     * @generated from protobuf rpc: MarketDataServerSideStream(tinkoff.public.invest.api.contract.v1.MarketDataServerSideStreamRequest) returns (stream tinkoff.public.invest.api.contract.v1.MarketDataResponse);
     */
    marketDataServerSideStream(input: MarketDataServerSideStreamRequest, options?: RpcOptions): ServerStreamingCall<MarketDataServerSideStreamRequest, MarketDataResponse>;
}
/**
 * @generated from protobuf service tinkoff.public.invest.api.contract.v1.MarketDataStreamService
 */
export class MarketDataStreamServiceClient implements IMarketDataStreamServiceClient, ServiceInfo {
    typeName = MarketDataStreamService.typeName;
    methods = MarketDataStreamService.methods;
    options = MarketDataStreamService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Bi-directional стрим предоставления биржевой информации.
     *
     * @generated from protobuf rpc: MarketDataStream(stream tinkoff.public.invest.api.contract.v1.MarketDataRequest) returns (stream tinkoff.public.invest.api.contract.v1.MarketDataResponse);
     */
    marketDataStream(options?: RpcOptions): DuplexStreamingCall<MarketDataRequest, MarketDataResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<MarketDataRequest, MarketDataResponse>("duplex", this._transport, method, opt);
    }
    /**
     * Server-side стрим предоставления биржевой информации.
     *
     * @generated from protobuf rpc: MarketDataServerSideStream(tinkoff.public.invest.api.contract.v1.MarketDataServerSideStreamRequest) returns (stream tinkoff.public.invest.api.contract.v1.MarketDataResponse);
     */
    marketDataServerSideStream(input: MarketDataServerSideStreamRequest, options?: RpcOptions): ServerStreamingCall<MarketDataServerSideStreamRequest, MarketDataResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<MarketDataServerSideStreamRequest, MarketDataResponse>("serverStreaming", this._transport, method, opt, input);
    }
}
