// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "sandbox.proto" (package "tinkoff.public.invest.api.contract.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SandboxService } from "./sandbox.js";
import type { WithdrawLimitsResponse } from "./operations.js";
import type { WithdrawLimitsRequest } from "./operations.js";
import type { SandboxPayInResponse } from "./sandbox.js";
import type { SandboxPayInRequest } from "./sandbox.js";
import type { PortfolioResponse } from "./operations.js";
import type { PortfolioRequest } from "./operations.js";
import type { GetOperationsByCursorResponse } from "./operations.js";
import type { GetOperationsByCursorRequest } from "./operations.js";
import type { OperationsResponse } from "./operations.js";
import type { OperationsRequest } from "./operations.js";
import type { PositionsResponse } from "./operations.js";
import type { PositionsRequest } from "./operations.js";
import type { OrderState } from "./orders.js";
import type { GetOrderStateRequest } from "./orders.js";
import type { CancelOrderResponse } from "./orders.js";
import type { CancelOrderRequest } from "./orders.js";
import type { GetOrdersResponse } from "./orders.js";
import type { GetOrdersRequest } from "./orders.js";
import type { ReplaceOrderRequest } from "./orders.js";
import type { PostOrderResponse } from "./orders.js";
import type { PostOrderRequest } from "./orders.js";
import type { CloseSandboxAccountResponse } from "./sandbox.js";
import type { CloseSandboxAccountRequest } from "./sandbox.js";
import type { GetAccountsResponse } from "./users.js";
import type { GetAccountsRequest } from "./users.js";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { OpenSandboxAccountResponse } from "./sandbox.js";
import type { OpenSandboxAccountRequest } from "./sandbox.js";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Сервис для работы с песочницей TINKOFF INVEST API
 *
 * @generated from protobuf service tinkoff.public.invest.api.contract.v1.SandboxService
 */
export interface ISandboxServiceClient {
    /**
     * Метод регистрации счёта в песочнице.
     *
     * @generated from protobuf rpc: OpenSandboxAccount(tinkoff.public.invest.api.contract.v1.OpenSandboxAccountRequest) returns (tinkoff.public.invest.api.contract.v1.OpenSandboxAccountResponse);
     */
    openSandboxAccount(input: OpenSandboxAccountRequest, options?: RpcOptions): UnaryCall<OpenSandboxAccountRequest, OpenSandboxAccountResponse>;
    /**
     * Метод получения счетов в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxAccounts(tinkoff.public.invest.api.contract.v1.GetAccountsRequest) returns (tinkoff.public.invest.api.contract.v1.GetAccountsResponse);
     */
    getSandboxAccounts(input: GetAccountsRequest, options?: RpcOptions): UnaryCall<GetAccountsRequest, GetAccountsResponse>;
    /**
     * Метод закрытия счёта в песочнице.
     *
     * @generated from protobuf rpc: CloseSandboxAccount(tinkoff.public.invest.api.contract.v1.CloseSandboxAccountRequest) returns (tinkoff.public.invest.api.contract.v1.CloseSandboxAccountResponse);
     */
    closeSandboxAccount(input: CloseSandboxAccountRequest, options?: RpcOptions): UnaryCall<CloseSandboxAccountRequest, CloseSandboxAccountResponse>;
    /**
     * Метод выставления торгового поручения в песочнице.
     *
     * @generated from protobuf rpc: PostSandboxOrder(tinkoff.public.invest.api.contract.v1.PostOrderRequest) returns (tinkoff.public.invest.api.contract.v1.PostOrderResponse);
     */
    postSandboxOrder(input: PostOrderRequest, options?: RpcOptions): UnaryCall<PostOrderRequest, PostOrderResponse>;
    /**
     * Метод изменения выставленной заявки.
     *
     * @generated from protobuf rpc: ReplaceSandboxOrder(tinkoff.public.invest.api.contract.v1.ReplaceOrderRequest) returns (tinkoff.public.invest.api.contract.v1.PostOrderResponse);
     */
    replaceSandboxOrder(input: ReplaceOrderRequest, options?: RpcOptions): UnaryCall<ReplaceOrderRequest, PostOrderResponse>;
    /**
     * Метод получения списка активных заявок по счёту в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxOrders(tinkoff.public.invest.api.contract.v1.GetOrdersRequest) returns (tinkoff.public.invest.api.contract.v1.GetOrdersResponse);
     */
    getSandboxOrders(input: GetOrdersRequest, options?: RpcOptions): UnaryCall<GetOrdersRequest, GetOrdersResponse>;
    /**
     * Метод отмены торгового поручения в песочнице.
     *
     * @generated from protobuf rpc: CancelSandboxOrder(tinkoff.public.invest.api.contract.v1.CancelOrderRequest) returns (tinkoff.public.invest.api.contract.v1.CancelOrderResponse);
     */
    cancelSandboxOrder(input: CancelOrderRequest, options?: RpcOptions): UnaryCall<CancelOrderRequest, CancelOrderResponse>;
    /**
     * Метод получения статуса заявки в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxOrderState(tinkoff.public.invest.api.contract.v1.GetOrderStateRequest) returns (tinkoff.public.invest.api.contract.v1.OrderState);
     */
    getSandboxOrderState(input: GetOrderStateRequest, options?: RpcOptions): UnaryCall<GetOrderStateRequest, OrderState>;
    /**
     * Метод получения позиций по виртуальному счёту песочницы.
     *
     * @generated from protobuf rpc: GetSandboxPositions(tinkoff.public.invest.api.contract.v1.PositionsRequest) returns (tinkoff.public.invest.api.contract.v1.PositionsResponse);
     */
    getSandboxPositions(input: PositionsRequest, options?: RpcOptions): UnaryCall<PositionsRequest, PositionsResponse>;
    /**
     * Метод получения операций в песочнице по номеру счёта.
     *
     * @generated from protobuf rpc: GetSandboxOperations(tinkoff.public.invest.api.contract.v1.OperationsRequest) returns (tinkoff.public.invest.api.contract.v1.OperationsResponse);
     */
    getSandboxOperations(input: OperationsRequest, options?: RpcOptions): UnaryCall<OperationsRequest, OperationsResponse>;
    /**
     * Метод получения операций в песочнице по номеру счета с пагинацией.
     *
     * @generated from protobuf rpc: GetSandboxOperationsByCursor(tinkoff.public.invest.api.contract.v1.GetOperationsByCursorRequest) returns (tinkoff.public.invest.api.contract.v1.GetOperationsByCursorResponse);
     */
    getSandboxOperationsByCursor(input: GetOperationsByCursorRequest, options?: RpcOptions): UnaryCall<GetOperationsByCursorRequest, GetOperationsByCursorResponse>;
    /**
     * Метод получения портфолио в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxPortfolio(tinkoff.public.invest.api.contract.v1.PortfolioRequest) returns (tinkoff.public.invest.api.contract.v1.PortfolioResponse);
     */
    getSandboxPortfolio(input: PortfolioRequest, options?: RpcOptions): UnaryCall<PortfolioRequest, PortfolioResponse>;
    /**
     * Метод пополнения счёта в песочнице.
     *
     * @generated from protobuf rpc: SandboxPayIn(tinkoff.public.invest.api.contract.v1.SandboxPayInRequest) returns (tinkoff.public.invest.api.contract.v1.SandboxPayInResponse);
     */
    sandboxPayIn(input: SandboxPayInRequest, options?: RpcOptions): UnaryCall<SandboxPayInRequest, SandboxPayInResponse>;
    /**
     * Метод получения доступного остатка для вывода средств в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxWithdrawLimits(tinkoff.public.invest.api.contract.v1.WithdrawLimitsRequest) returns (tinkoff.public.invest.api.contract.v1.WithdrawLimitsResponse);
     */
    getSandboxWithdrawLimits(input: WithdrawLimitsRequest, options?: RpcOptions): UnaryCall<WithdrawLimitsRequest, WithdrawLimitsResponse>;
}
/**
 * Сервис для работы с песочницей TINKOFF INVEST API
 *
 * @generated from protobuf service tinkoff.public.invest.api.contract.v1.SandboxService
 */
export class SandboxServiceClient implements ISandboxServiceClient, ServiceInfo {
    typeName = SandboxService.typeName;
    methods = SandboxService.methods;
    options = SandboxService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Метод регистрации счёта в песочнице.
     *
     * @generated from protobuf rpc: OpenSandboxAccount(tinkoff.public.invest.api.contract.v1.OpenSandboxAccountRequest) returns (tinkoff.public.invest.api.contract.v1.OpenSandboxAccountResponse);
     */
    openSandboxAccount(input: OpenSandboxAccountRequest, options?: RpcOptions): UnaryCall<OpenSandboxAccountRequest, OpenSandboxAccountResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<OpenSandboxAccountRequest, OpenSandboxAccountResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод получения счетов в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxAccounts(tinkoff.public.invest.api.contract.v1.GetAccountsRequest) returns (tinkoff.public.invest.api.contract.v1.GetAccountsResponse);
     */
    getSandboxAccounts(input: GetAccountsRequest, options?: RpcOptions): UnaryCall<GetAccountsRequest, GetAccountsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAccountsRequest, GetAccountsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод закрытия счёта в песочнице.
     *
     * @generated from protobuf rpc: CloseSandboxAccount(tinkoff.public.invest.api.contract.v1.CloseSandboxAccountRequest) returns (tinkoff.public.invest.api.contract.v1.CloseSandboxAccountResponse);
     */
    closeSandboxAccount(input: CloseSandboxAccountRequest, options?: RpcOptions): UnaryCall<CloseSandboxAccountRequest, CloseSandboxAccountResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CloseSandboxAccountRequest, CloseSandboxAccountResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод выставления торгового поручения в песочнице.
     *
     * @generated from protobuf rpc: PostSandboxOrder(tinkoff.public.invest.api.contract.v1.PostOrderRequest) returns (tinkoff.public.invest.api.contract.v1.PostOrderResponse);
     */
    postSandboxOrder(input: PostOrderRequest, options?: RpcOptions): UnaryCall<PostOrderRequest, PostOrderResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostOrderRequest, PostOrderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод изменения выставленной заявки.
     *
     * @generated from protobuf rpc: ReplaceSandboxOrder(tinkoff.public.invest.api.contract.v1.ReplaceOrderRequest) returns (tinkoff.public.invest.api.contract.v1.PostOrderResponse);
     */
    replaceSandboxOrder(input: ReplaceOrderRequest, options?: RpcOptions): UnaryCall<ReplaceOrderRequest, PostOrderResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReplaceOrderRequest, PostOrderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод получения списка активных заявок по счёту в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxOrders(tinkoff.public.invest.api.contract.v1.GetOrdersRequest) returns (tinkoff.public.invest.api.contract.v1.GetOrdersResponse);
     */
    getSandboxOrders(input: GetOrdersRequest, options?: RpcOptions): UnaryCall<GetOrdersRequest, GetOrdersResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOrdersRequest, GetOrdersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод отмены торгового поручения в песочнице.
     *
     * @generated from protobuf rpc: CancelSandboxOrder(tinkoff.public.invest.api.contract.v1.CancelOrderRequest) returns (tinkoff.public.invest.api.contract.v1.CancelOrderResponse);
     */
    cancelSandboxOrder(input: CancelOrderRequest, options?: RpcOptions): UnaryCall<CancelOrderRequest, CancelOrderResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelOrderRequest, CancelOrderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод получения статуса заявки в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxOrderState(tinkoff.public.invest.api.contract.v1.GetOrderStateRequest) returns (tinkoff.public.invest.api.contract.v1.OrderState);
     */
    getSandboxOrderState(input: GetOrderStateRequest, options?: RpcOptions): UnaryCall<GetOrderStateRequest, OrderState> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOrderStateRequest, OrderState>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод получения позиций по виртуальному счёту песочницы.
     *
     * @generated from protobuf rpc: GetSandboxPositions(tinkoff.public.invest.api.contract.v1.PositionsRequest) returns (tinkoff.public.invest.api.contract.v1.PositionsResponse);
     */
    getSandboxPositions(input: PositionsRequest, options?: RpcOptions): UnaryCall<PositionsRequest, PositionsResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<PositionsRequest, PositionsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод получения операций в песочнице по номеру счёта.
     *
     * @generated from protobuf rpc: GetSandboxOperations(tinkoff.public.invest.api.contract.v1.OperationsRequest) returns (tinkoff.public.invest.api.contract.v1.OperationsResponse);
     */
    getSandboxOperations(input: OperationsRequest, options?: RpcOptions): UnaryCall<OperationsRequest, OperationsResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<OperationsRequest, OperationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод получения операций в песочнице по номеру счета с пагинацией.
     *
     * @generated from protobuf rpc: GetSandboxOperationsByCursor(tinkoff.public.invest.api.contract.v1.GetOperationsByCursorRequest) returns (tinkoff.public.invest.api.contract.v1.GetOperationsByCursorResponse);
     */
    getSandboxOperationsByCursor(input: GetOperationsByCursorRequest, options?: RpcOptions): UnaryCall<GetOperationsByCursorRequest, GetOperationsByCursorResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOperationsByCursorRequest, GetOperationsByCursorResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод получения портфолио в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxPortfolio(tinkoff.public.invest.api.contract.v1.PortfolioRequest) returns (tinkoff.public.invest.api.contract.v1.PortfolioResponse);
     */
    getSandboxPortfolio(input: PortfolioRequest, options?: RpcOptions): UnaryCall<PortfolioRequest, PortfolioResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<PortfolioRequest, PortfolioResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод пополнения счёта в песочнице.
     *
     * @generated from protobuf rpc: SandboxPayIn(tinkoff.public.invest.api.contract.v1.SandboxPayInRequest) returns (tinkoff.public.invest.api.contract.v1.SandboxPayInResponse);
     */
    sandboxPayIn(input: SandboxPayInRequest, options?: RpcOptions): UnaryCall<SandboxPayInRequest, SandboxPayInResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<SandboxPayInRequest, SandboxPayInResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Метод получения доступного остатка для вывода средств в песочнице.
     *
     * @generated from protobuf rpc: GetSandboxWithdrawLimits(tinkoff.public.invest.api.contract.v1.WithdrawLimitsRequest) returns (tinkoff.public.invest.api.contract.v1.WithdrawLimitsResponse);
     */
    getSandboxWithdrawLimits(input: WithdrawLimitsRequest, options?: RpcOptions): UnaryCall<WithdrawLimitsRequest, WithdrawLimitsResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<WithdrawLimitsRequest, WithdrawLimitsResponse>("unary", this._transport, method, opt, input);
    }
}
